// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWAvBokHvOLFDrpooKUoNluWu5Rrk3QJ0',
    appId: '1:245622381531:web:34dfec1e18df86b6da25fe',
    messagingSenderId: '245622381531',
    projectId: 'my-app-8c059',
    authDomain: 'my-app-8c059.firebaseapp.com',
    storageBucket: 'my-app-8c059.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYLUwhdbtFKR4CV4O_nw0jpaZn4d0FD0',
    appId: '1:245622381531:android:96d28c22c97d5f67da25fe',
    messagingSenderId: '245622381531',
    projectId: 'my-app-8c059',
    storageBucket: 'my-app-8c059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHBxSy0zuHCN0OumB_7J7pV323GpUYOGo',
    appId: '1:245622381531:ios:8ed727efe2c25afcda25fe',
    messagingSenderId: '245622381531',
    projectId: 'my-app-8c059',
    storageBucket: 'my-app-8c059.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHBxSy0zuHCN0OumB_7J7pV323GpUYOGo',
    appId: '1:245622381531:ios:c98cdb6e86523682da25fe',
    messagingSenderId: '245622381531',
    projectId: 'my-app-8c059',
    storageBucket: 'my-app-8c059.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
